In [8]:
# Basic
import pandas as pd
import numpy as np

import re
%pip install nltk
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report
nltk.download('stopwords')
nltk.download('wordnet')

Requirement already satisfied: nltk in c:\users\dilip\appdata\local\programs\python\python312\lib\site-packages (3.9.4)
Requirement already satisfied: click in c:\users\dilip\appdata\local\programs\python\python312\lib\site-packages (from nltk) (8.1.7)
Requirement already satisfied: joblib in c:\users\dilip\appdata\local\programs\python\python312\lib\site-packages (from nltk) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\dilip\appdata\local\programs\python\python312\lib\site-packages (from nltk) (2024.11.6)
Requirement already satisfied: tqdm in c:\users\dilip\appdata\local\programs\python\python312\lib\site-packages (from nltk) (4.66.5)
Requirement already satisfied: colorama in c:\users\dilip\appdata\local\programs\python\python312\lib\site-packages (from click->nltk) (0.4.6)

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\dilip\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\dilip\AppData\Roaming\nltk_data...

True

In [9]:
df = pd.read_csv("IMDB Dataset.csv")

df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [10]:
print("Shape:", df.shape)
print("\nClass Distribution:\n", df['sentiment'].value_counts())

df.sample(5)

Shape: (50000, 2)

Class Distribution:
 sentiment
positive    25000
negative    25000
Name: count, dtype: int64

                                                  review sentiment
35751  This is my favorite movie EVER. I have watched...  positive
11612  Rumor has it that when the NASA Technical Advi...  negative
4203   Nice description of the situation in the US, i...  positive
18185  It is one of the joys of Shakespeare that ther...  negative
49331  I really don't get how people made this film a...  negative

## Data Understanding

- Dataset contains movie reviews with sentiment labels (positive/negative)
- Total samples: 50,000
- Balanced dataset (equal positive and negative reviews)

In [11]:
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def preprocess_text(text):
    text = text.lower()
    text = re.sub(r"http\S+", "", text)
    text = re.sub(r"[^a-zA-Z]", " ", text) 
    
    words = text.split()
    
    words = [w for w in words if w not in stop_words]
    words = [lemmatizer.lemmatize(w) for w in words]
    
    return " ".join(words)

In [12]:
df['clean_text'] = df['review'].apply(preprocess_text)

## NLP Preprocessing Steps

- Converted text to lowercase
- Removed URLs and special characters
- Tokenized text
- Removed stopwords
- Applied lemmatization

These steps help reduce noise and improve model performance.

In [13]:
df['label'] = df['sentiment'].map({'positive':1, 'negative':0})

In [14]:
X = df['clean_text']
y = df['label']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [15]:
bow = CountVectorizer(max_features=5000)

X_train_bow = bow.fit_transform(X_train)
X_test_bow = bow.transform(X_test)

In [16]:
tfidf = TfidfVectorizer(max_features=5000)

X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

## Feature Engineering

Two techniques were used:

1. Bag of Words (BoW)
   - Counts word frequency
   - Simple but ignores importance

2. TF-IDF
   - Weighs words based on importance
   - Reduces impact of common words

TF-IDF usually performs better in NLP tasks.

In [17]:
def evaluate_model(model, X_train, X_test, y_train, y_test, name):
    model.fit(X_train, y_train)
    
    y_pred = model.predict(X_test)
    
    print(f"\n{name} Results")
    print("-"*40)
    print("Accuracy:", accuracy_score(y_test, y_pred))
    print("Precision:", precision_score(y_test, y_pred))
    print("Recall:", recall_score(y_test, y_pred))
    print("F1 Score:", f1_score(y_test, y_pred))
    
    print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
    print("\nClassification Report:\n", classification_report(y_test, y_pred))

In [22]:
evaluate_model(LogisticRegression(max_iter=1000), X_train_bow, X_test_bow, y_train, y_test, "Logistic Regression")

evaluate_model(MultinomialNB(), X_train_bow, X_test_bow, y_train, y_test, "Naive Bayes")

evaluate_model(DecisionTreeClassifier(), X_train_bow, X_test_bow, y_train, y_test, "Decision Tree")

Logistic Regression Results
----------------------------------------
Accuracy: 0.8728
Precision: 0.8710191082802548
Recall: 0.8752
F1 Score: 0.8731045490822027

Confusion Matrix:
 [[4352  648]
 [ 624 4376]]

Classification Report:
               precision    recall  f1-score   support

           0       0.87      0.87      0.87      5000
           1       0.87      0.88      0.87      5000

    accuracy                           0.87     10000
   macro avg       0.87      0.87      0.87     10000
weighted avg       0.87      0.87      0.87     10000


Naive Bayes Results
----------------------------------------
Accuracy: 0.85
Precision: 0.851123595505618
Recall: 0.8484
F1 Score: 0.8497596153846154

Confusion Matrix:
 [[4258  742]
 [ 758 4242]]

Classification Report:
               precision    recall  f1-score   support

           0       0.85      0.85      0.85      5000
           1       0.85      0.85      0.85      5000

    accuracy                           0.85     10000
   macro avg       0.85      0.85      0.85     10000
weighted avg       0.85      0.85      0.85     10000


Decision Tree Results
----------------------------------------
Accuracy: 0.7139
Precision: 0.7129205653991638
Recall: 0.7162
F1 Score: 0.7145565200039908

Confusion Matrix:
 [[3558 1442]
 [1419 3581]]

Classification Report:
               precision    recall  f1-score   support

           0       0.71      0.71      0.71      5000
           1       0.71      0.72      0.71      5000

    accuracy                           0.71     10000
   macro avg       0.71      0.71      0.71     10000
weighted avg       0.71      0.71      0.71     10000

In [23]:
evaluate_model(LogisticRegression(max_iter=1000), X_train_tfidf, X_test_tfidf, y_train, y_test, "Logistic Regression")

evaluate_model(MultinomialNB(), X_train_tfidf, X_test_tfidf, y_train, y_test, "Naive Bayes")

evaluate_model(DecisionTreeClassifier(), X_train_tfidf, X_test_tfidf, y_train, y_test, "Decision Tree")

Logistic Regression Results
----------------------------------------
Accuracy: 0.8906
Precision: 0.8832417582417582
Recall: 0.9002
F1 Score: 0.8916402535657686

Confusion Matrix:
 [[4405  595]
 [ 499 4501]]

Classification Report:
               precision    recall  f1-score   support

           0       0.90      0.88      0.89      5000
           1       0.88      0.90      0.89      5000

    accuracy                           0.89     10000
   macro avg       0.89      0.89      0.89     10000
weighted avg       0.89      0.89      0.89     10000


Naive Bayes Results
----------------------------------------
Accuracy: 0.8543
Precision: 0.8482406133280912
Recall: 0.863
F1 Score: 0.8555566570833747

Confusion Matrix:
 [[4228  772]
 [ 685 4315]]

Classification Report:
               precision    recall  f1-score   support

           0       0.86      0.85      0.85      5000
           1       0.85      0.86      0.86      5000

    accuracy                           0.85     10000
   macro avg       0.85      0.85      0.85     10000
weighted avg       0.85      0.85      0.85     10000


Decision Tree Results
----------------------------------------
Accuracy: 0.7248
Precision: 0.727254346947028
Recall: 0.7194
F1 Score: 0.7233058515986326

Confusion Matrix:
 [[3651 1349]
 [1403 3597]]

Classification Report:
               precision    recall  f1-score   support

           0       0.72      0.73      0.73      5000
           1       0.73      0.72      0.72      5000

    accuracy                           0.72     10000
   macro avg       0.72      0.72      0.72     10000
weighted avg       0.72      0.72      0.72     10000

## Final Insights & Comparison

1. Dataset:
The IMDb dataset is balanced, making it suitable for classification tasks.

2. Preprocessing:
Text cleaning, stopword removal, and lemmatization significantly improved model performance.

3. Feature Engineering:
- TF-IDF outperformed Bag of Words
- It captures word importance effectively

4. Model Comparison:
- Logistic Regression performed the best overall
- Naive Bayes was fast but slightly less accurate
- Decision Tree showed signs of overfitting

5. Best Model:
Logistic Regression with TF-IDF achieved the best balance of accuracy and generalization.

6. Trade-offs:
- Logistic Regression: Best accuracy
- Naive Bayes: Fastest
- Decision Tree: Less stable